Upstream/issue 6114
ant-media/WebRTC-iOS-SDK pull request #41
Opened 2024-03-21 02:56 UTC by MuhammadjonTohirov

Audio stream reactivation should work.

2024-04-10 10:22 UTC, mekya requested changes
Hi @MuhammadjonTohirov,

Thank you for the implementation. I've some requests to change. Could you please check it?

Cheers
Oguz

2024-04-10 10:22 UTC, mekya commented on ScreenShare/ScreenShare.entitlements
> -	<array>
Please let me know what is the advantage of removing group info in the code

2024-04-10 10:22 UTC, mekya commented on WebRTC-Sample-App/WebRTC-Sample-App.entitlements
> -	<array>
Please let me know what is the advantage of removing group info in the code

2024-04-10 10:22 UTC, mekya commented on WebRTC-Sample-App/WebRTC-Sample-AppDebug.entitlements
> -	<array>
Please let me know what is the advantage of removing group info in the code

2024-04-10 10:22 UTC, mekya commented on WebRTCiOSSDK.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +{
Currently we use 4.0.6, it's 4.04 and we encounter a problem previously because Package.resolved is in the repo. Could you please delete it and adapt the changes for 4.0.6 again?

2024-04-10 10:22 UTC, mekya commented on WebRTCiOSSDK/api/AntMediaClient+Audio.swift
> +extension AntMediaClient {
Thank you for the implementation. Let me try it.

2024-04-10 10:22 UTC, mekya commented on WebRTCiOSSDK/api/AntMediaClient.swift
> +    public func didReceive(event: Starscream.WebSocketEvent, client: Starscream.WebSocket) {
Please adapt it with StarScream 4.0.6

2024-05-21 12:28 UTC, MuhammadjonTohirov commented on ScreenShare/ScreenShare.entitlements
> -	<array>
Hi, @mekya 
I did not see your comment, my bad. I'll do it and create another pull request.

2024-06-02 13:25 UTC, mekya commented
Hi @MuhammadjonTohirov ,

You've created the PR to fix this issue 
https://github.com/ant-media/WebRTC-iOS-SDK/pull/51

then I'm closing this PR

Thank you

Cheers

2024-06-02 13:25 UTC, closed without merging